const variable = {
  APPWRITE_PROJECT: process.env.EXPO_PUBLIC_APPWRITE_PROJECT!,
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
  APPWRITE_PLATFORM: process.env.EXPO_PUBLIC_APPWRITE_PLATFORM!,

  DATABASE_PRIMARY: process.env.EXPO_PUBLIC_DATABASE_PRIMARY!,
  COLLECTION_CREDENTIALS: process.env.EXPO_PUBLIC_COLLECTION_CREDENTIALS!,
  COLLECTION_USER: process.env.EXPO_PUBLIC_COLLECTION_USER!,
  COLLECTION_LOG: process.env.EXPO_PUBLIC_COLLECTION_LOG!,
  COLLECTION_DEVICE: process.env.EXPO_PUBLIC_COLLECTION_DEVICE!,
  FUNCTION_ACCOUNT: process.env.EXPO_PUBLIC_FUNCTION_ACCOUNT!,
  FUNCTION_LOGGING: process.env.EXPO_PUBLIC_FUNCTION_LOGGING!,
  BUCKET_IMAGE: process.env.EXPO_PUBLIC_BUCKET_IMAGE!,
};

export const env = variable;
